services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: pleasenote
      POSTGRES_USER: pleasenote
      POSTGRES_PASSWORD: pleasenote
    ports:
      - "5432:5432"
    volumes:
      - pleasenote_pg:/var/lib/postgresql/data
volumes:
  pleasenote_pg:
